/* Automatically @generated by tree-sitter v0.25.7 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_document_token1 = 1,
  anon_sym_PIPE = 2,
  sym_text = 3,
  aux_sym_number_token1 = 4,
  aux_sym_number_token2 = 5,
  aux_sym_float_token1 = 6,
  aux_sym_float_token2 = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  sym_empty_field = 10,
  sym__error_sentinel = 11,
  sym_document = 12,
  sym_row = 13,
  sym_field = 14,
  sym_number = 15,
  sym_float = 16,
  sym_boolean = 17,
  aux_sym_document_repeat1 = 18,
  aux_sym_row_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_document_token1] = "document_token1",
  [anon_sym_PIPE] = "|",
  [sym_text] = "text",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_float_token1] = "float_token1",
  [aux_sym_float_token2] = "float_token2",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_empty_field] = "empty_field",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_document] = "document",
  [sym_row] = "row",
  [sym_field] = "field",
  [sym_number] = "number",
  [sym_float] = "float",
  [sym_boolean] = "boolean",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_row_repeat1] = "row_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_document_token1] = aux_sym_document_token1,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [sym_text] = sym_text,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [aux_sym_float_token2] = aux_sym_float_token2,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_empty_field] = sym_empty_field,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_document] = sym_document,
  [sym_row] = sym_row,
  [sym_field] = sym_field,
  [sym_number] = sym_number,
  [sym_float] = sym_float,
  [sym_boolean] = sym_boolean,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_row_repeat1] = aux_sym_row_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_empty_field] = {
    .visible = true,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_row] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_row_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 4,
  [9] = 5,
  [10] = 10,
  [11] = 11,
  [12] = 10,
  [13] = 11,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 17,
  [25] = 18,
  [26] = 19,
  [27] = 15,
  [28] = 28,
  [29] = 16,
  [30] = 30,
  [31] = 31,
  [32] = 20,
  [33] = 23,
  [34] = 28,
  [35] = 21,
  [36] = 22,
  [37] = 37,
  [38] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(4);
      ADVANCE_MAP(
        '\n', 5,
        '\r', 5,
        '"', 1,
        '.', 15,
        '0', 17,
        'f', 8,
        't', 12,
        '|', 6,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(7);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 3:
      if (eof) ADVANCE(4);
      if (lookahead == '"') ADVANCE(1);
      if (lookahead == '.') ADVANCE(15);
      if (lookahead == '0') ADVANCE(17);
      if (lookahead == 'f') ADVANCE(8);
      if (lookahead == 't') ADVANCE(12);
      if (lookahead == '|') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(18);
      if (lookahead != 0) ADVANCE(16);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(aux_sym_document_token1);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '\r') ADVANCE(5);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '"') ADVANCE(1);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(11);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(13);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(10);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_text);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(21);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_number_token1);
      if (lookahead == '.') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_number_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_float_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_float_token2);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '|') ADVANCE(16);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 3, .external_lex_state = 2},
  [2] = {.lex_state = 3, .external_lex_state = 2},
  [3] = {.lex_state = 3, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 2},
  [6] = {.lex_state = 0, .external_lex_state = 2},
  [7] = {.lex_state = 0, .external_lex_state = 2},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 3, .external_lex_state = 2},
  [11] = {.lex_state = 3, .external_lex_state = 2},
  [12] = {.lex_state = 3, .external_lex_state = 2},
  [13] = {.lex_state = 3, .external_lex_state = 2},
  [14] = {.lex_state = 3, .external_lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_document_token1] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_float_token1] = ACTIONS(1),
    [aux_sym_float_token2] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_empty_field] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(37),
    [sym_row] = STATE(31),
    [sym_field] = STATE(18),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_PIPE] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(11),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_empty_field] = ACTIONS(17),
  },
  [STATE(2)] = {
    [sym_row] = STATE(38),
    [sym_field] = STATE(25),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_PIPE] = ACTIONS(21),
    [sym_text] = ACTIONS(24),
    [aux_sym_number_token1] = ACTIONS(27),
    [aux_sym_number_token2] = ACTIONS(30),
    [aux_sym_float_token1] = ACTIONS(33),
    [aux_sym_float_token2] = ACTIONS(33),
    [anon_sym_true] = ACTIONS(36),
    [anon_sym_false] = ACTIONS(36),
    [sym_empty_field] = ACTIONS(39),
  },
  [STATE(3)] = {
    [sym_row] = STATE(30),
    [sym_field] = STATE(18),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(42),
    [anon_sym_PIPE] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(11),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_empty_field] = ACTIONS(17),
  },
  [STATE(4)] = {
    [sym_field] = STATE(22),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(44),
    [aux_sym_document_token1] = ACTIONS(44),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_empty_field] = ACTIONS(17),
  },
  [STATE(5)] = {
    [sym_field] = STATE(22),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(46),
    [aux_sym_document_token1] = ACTIONS(46),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_empty_field] = ACTIONS(17),
  },
  [STATE(6)] = {
    [sym_field] = STATE(22),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(48),
    [aux_sym_document_token1] = ACTIONS(48),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_empty_field] = ACTIONS(17),
  },
  [STATE(7)] = {
    [sym_field] = STATE(36),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [aux_sym_document_token1] = ACTIONS(48),
    [sym_text] = ACTIONS(50),
    [aux_sym_number_token1] = ACTIONS(52),
    [aux_sym_number_token2] = ACTIONS(52),
    [aux_sym_float_token1] = ACTIONS(54),
    [aux_sym_float_token2] = ACTIONS(54),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_empty_field] = ACTIONS(58),
  },
  [STATE(8)] = {
    [sym_field] = STATE(36),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [aux_sym_document_token1] = ACTIONS(44),
    [sym_text] = ACTIONS(50),
    [aux_sym_number_token1] = ACTIONS(52),
    [aux_sym_number_token2] = ACTIONS(52),
    [aux_sym_float_token1] = ACTIONS(54),
    [aux_sym_float_token2] = ACTIONS(54),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_empty_field] = ACTIONS(58),
  },
  [STATE(9)] = {
    [sym_field] = STATE(36),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [aux_sym_document_token1] = ACTIONS(46),
    [sym_text] = ACTIONS(50),
    [aux_sym_number_token1] = ACTIONS(52),
    [aux_sym_number_token2] = ACTIONS(52),
    [aux_sym_float_token1] = ACTIONS(54),
    [aux_sym_float_token2] = ACTIONS(54),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_empty_field] = ACTIONS(58),
  },
  [STATE(10)] = {
    [sym_field] = STATE(19),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(11),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_empty_field] = ACTIONS(17),
  },
  [STATE(11)] = {
    [sym_field] = STATE(22),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(11),
    [aux_sym_float_token1] = ACTIONS(13),
    [aux_sym_float_token2] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [sym_empty_field] = ACTIONS(17),
  },
  [STATE(12)] = {
    [sym_field] = STATE(26),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [sym_text] = ACTIONS(50),
    [aux_sym_number_token1] = ACTIONS(52),
    [aux_sym_number_token2] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(54),
    [aux_sym_float_token2] = ACTIONS(54),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_empty_field] = ACTIONS(58),
  },
  [STATE(13)] = {
    [sym_field] = STATE(36),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [sym_text] = ACTIONS(50),
    [aux_sym_number_token1] = ACTIONS(52),
    [aux_sym_number_token2] = ACTIONS(60),
    [aux_sym_float_token1] = ACTIONS(54),
    [aux_sym_float_token2] = ACTIONS(54),
    [anon_sym_true] = ACTIONS(56),
    [anon_sym_false] = ACTIONS(56),
    [sym_empty_field] = ACTIONS(58),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(19), 4,
      sym_empty_field,
      ts_builtin_sym_end,
      anon_sym_PIPE,
      aux_sym_number_token2,
    ACTIONS(62), 6,
      sym_text,
      aux_sym_number_token1,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_true,
      anon_sym_false,
  [15] = 3,
    ACTIONS(66), 1,
      anon_sym_PIPE,
    STATE(15), 1,
      aux_sym_row_repeat1,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [26] = 3,
    ACTIONS(69), 1,
      anon_sym_PIPE,
    STATE(15), 1,
      aux_sym_row_repeat1,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [37] = 3,
    ACTIONS(71), 1,
      anon_sym_PIPE,
    STATE(15), 1,
      aux_sym_row_repeat1,
    ACTIONS(46), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [48] = 3,
    ACTIONS(75), 1,
      anon_sym_PIPE,
    STATE(16), 1,
      aux_sym_row_repeat1,
    ACTIONS(73), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [59] = 3,
    ACTIONS(69), 1,
      anon_sym_PIPE,
    STATE(17), 1,
      aux_sym_row_repeat1,
    ACTIONS(44), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [70] = 2,
    ACTIONS(79), 1,
      anon_sym_PIPE,
    ACTIONS(77), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [78] = 2,
    ACTIONS(83), 1,
      anon_sym_PIPE,
    ACTIONS(81), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [86] = 2,
    ACTIONS(85), 1,
      anon_sym_PIPE,
    ACTIONS(64), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [94] = 2,
    ACTIONS(89), 1,
      anon_sym_PIPE,
    ACTIONS(87), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [102] = 3,
    ACTIONS(46), 1,
      aux_sym_document_token1,
    ACTIONS(91), 1,
      anon_sym_PIPE,
    STATE(27), 1,
      aux_sym_row_repeat1,
  [112] = 3,
    ACTIONS(73), 1,
      aux_sym_document_token1,
    ACTIONS(93), 1,
      anon_sym_PIPE,
    STATE(29), 1,
      aux_sym_row_repeat1,
  [122] = 3,
    ACTIONS(44), 1,
      aux_sym_document_token1,
    ACTIONS(95), 1,
      anon_sym_PIPE,
    STATE(24), 1,
      aux_sym_row_repeat1,
  [132] = 3,
    ACTIONS(64), 1,
      aux_sym_document_token1,
    ACTIONS(97), 1,
      anon_sym_PIPE,
    STATE(27), 1,
      aux_sym_row_repeat1,
  [142] = 2,
    ACTIONS(102), 1,
      anon_sym_PIPE,
    ACTIONS(100), 2,
      ts_builtin_sym_end,
      aux_sym_document_token1,
  [150] = 3,
    ACTIONS(44), 1,
      aux_sym_document_token1,
    ACTIONS(95), 1,
      anon_sym_PIPE,
    STATE(27), 1,
      aux_sym_row_repeat1,
  [160] = 2,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 1,
      aux_sym_document_token1,
  [167] = 2,
    ACTIONS(42), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 1,
      aux_sym_document_token1,
  [174] = 2,
    ACTIONS(77), 1,
      aux_sym_document_token1,
    ACTIONS(79), 1,
      anon_sym_PIPE,
  [181] = 2,
    ACTIONS(87), 1,
      aux_sym_document_token1,
    ACTIONS(89), 1,
      anon_sym_PIPE,
  [188] = 2,
    ACTIONS(100), 1,
      aux_sym_document_token1,
    ACTIONS(102), 1,
      anon_sym_PIPE,
  [195] = 2,
    ACTIONS(81), 1,
      aux_sym_document_token1,
    ACTIONS(83), 1,
      anon_sym_PIPE,
  [202] = 2,
    ACTIONS(64), 1,
      aux_sym_document_token1,
    ACTIONS(85), 1,
      anon_sym_PIPE,
  [209] = 1,
    ACTIONS(108), 1,
      ts_builtin_sym_end,
  [213] = 1,
    ACTIONS(106), 1,
      aux_sym_document_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 15,
  [SMALL_STATE(16)] = 26,
  [SMALL_STATE(17)] = 37,
  [SMALL_STATE(18)] = 48,
  [SMALL_STATE(19)] = 59,
  [SMALL_STATE(20)] = 70,
  [SMALL_STATE(21)] = 78,
  [SMALL_STATE(22)] = 86,
  [SMALL_STATE(23)] = 94,
  [SMALL_STATE(24)] = 102,
  [SMALL_STATE(25)] = 112,
  [SMALL_STATE(26)] = 122,
  [SMALL_STATE(27)] = 132,
  [SMALL_STATE(28)] = 142,
  [SMALL_STATE(29)] = 150,
  [SMALL_STATE(30)] = 160,
  [SMALL_STATE(31)] = 167,
  [SMALL_STATE(32)] = 174,
  [SMALL_STATE(33)] = 181,
  [SMALL_STATE(34)] = 188,
  [SMALL_STATE(35)] = 195,
  [SMALL_STATE(36)] = 202,
  [SMALL_STATE(37)] = 209,
  [SMALL_STATE(38)] = 213,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [24] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 3, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 4, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [62] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 1, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [108] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_empty_field = 0,
  ts_external_token__error_sentinel = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_empty_field] = sym_empty_field,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_empty_field] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token_empty_field] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_psv_external_scanner_create(void);
void tree_sitter_psv_external_scanner_destroy(void *);
bool tree_sitter_psv_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_psv_external_scanner_serialize(void *, char *);
void tree_sitter_psv_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_psv(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_psv_external_scanner_create,
      tree_sitter_psv_external_scanner_destroy,
      tree_sitter_psv_external_scanner_scan,
      tree_sitter_psv_external_scanner_serialize,
      tree_sitter_psv_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
