/* Automatically @generated by tree-sitter v0.25.7 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 14
#define SYMBOL_COUNT 20
#define ALIAS_COUNT 0
#define TOKEN_COUNT 12
#define EXTERNAL_TOKEN_COUNT 2
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_document_token1 = 1,
  anon_sym_TAB = 2,
  sym_text = 3,
  aux_sym_number_token1 = 4,
  aux_sym_number_token2 = 5,
  aux_sym_float_token1 = 6,
  aux_sym_float_token2 = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  sym_empty_field = 10,
  sym__error_sentinel = 11,
  sym_document = 12,
  sym_row = 13,
  sym_field = 14,
  sym_number = 15,
  sym_float = 16,
  sym_boolean = 17,
  aux_sym_document_repeat1 = 18,
  aux_sym_row_repeat1 = 19,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_document_token1] = "document_token1",
  [anon_sym_TAB] = "\t",
  [sym_text] = "text",
  [aux_sym_number_token1] = "number_token1",
  [aux_sym_number_token2] = "number_token2",
  [aux_sym_float_token1] = "float_token1",
  [aux_sym_float_token2] = "float_token2",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_empty_field] = "empty_field",
  [sym__error_sentinel] = "_error_sentinel",
  [sym_document] = "document",
  [sym_row] = "row",
  [sym_field] = "field",
  [sym_number] = "number",
  [sym_float] = "float",
  [sym_boolean] = "boolean",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_row_repeat1] = "row_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_document_token1] = aux_sym_document_token1,
  [anon_sym_TAB] = anon_sym_TAB,
  [sym_text] = sym_text,
  [aux_sym_number_token1] = aux_sym_number_token1,
  [aux_sym_number_token2] = aux_sym_number_token2,
  [aux_sym_float_token1] = aux_sym_float_token1,
  [aux_sym_float_token2] = aux_sym_float_token2,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_empty_field] = sym_empty_field,
  [sym__error_sentinel] = sym__error_sentinel,
  [sym_document] = sym_document,
  [sym_row] = sym_row,
  [sym_field] = sym_field,
  [sym_number] = sym_number,
  [sym_float] = sym_float,
  [sym_boolean] = sym_boolean,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_row_repeat1] = aux_sym_row_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_TAB] = {
    .visible = true,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_number_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_number_token2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_float_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_empty_field] = {
    .visible = true,
    .named = true,
  },
  [sym__error_sentinel] = {
    .visible = false,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_row] = {
    .visible = true,
    .named = true,
  },
  [sym_field] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_float] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_row_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 4,
  [9] = 5,
  [10] = 10,
  [11] = 11,
  [12] = 10,
  [13] = 11,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 17,
  [25] = 18,
  [26] = 19,
  [27] = 15,
  [28] = 28,
  [29] = 16,
  [30] = 30,
  [31] = 31,
  [32] = 20,
  [33] = 23,
  [34] = 28,
  [35] = 21,
  [36] = 22,
  [37] = 37,
  [38] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      ADVANCE_MAP(
        '\t', 8,
        '\n', 6,
        '\r', 6,
        '"', 2,
        '.', 20,
        '0', 11,
        'f', 13,
        't', 17,
      );
      if (lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(0);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '0') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(13);
      if (lookahead == 't') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(10);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (eof) ADVANCE(5);
      if (lookahead == '\t') ADVANCE(9);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '0') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(13);
      if (lookahead == 't') ADVANCE(17);
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(22);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(7);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == '0') ADVANCE(11);
      if (lookahead == 'f') ADVANCE(13);
      if (lookahead == 't') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(4);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != ',') ADVANCE(22);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(aux_sym_document_token1);
      if (lookahead == '\t') ADVANCE(8);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(aux_sym_document_token1);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '\r') ADVANCE(7);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead == '\t') ADVANCE(8);
      if (lookahead == '\n') ADVANCE(6);
      if (lookahead == '\r') ADVANCE(6);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_TAB);
      if (lookahead == '\t') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '"') ADVANCE(2);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '.') ADVANCE(20);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '.') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(23);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(18);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(15);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'u') ADVANCE(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_text);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(20);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_text);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"') ADVANCE(22);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 3, .external_lex_state = 2},
  [2] = {.lex_state = 3, .external_lex_state = 2},
  [3] = {.lex_state = 3, .external_lex_state = 2},
  [4] = {.lex_state = 4, .external_lex_state = 2},
  [5] = {.lex_state = 4, .external_lex_state = 2},
  [6] = {.lex_state = 4, .external_lex_state = 2},
  [7] = {.lex_state = 4, .external_lex_state = 2},
  [8] = {.lex_state = 4, .external_lex_state = 2},
  [9] = {.lex_state = 4, .external_lex_state = 2},
  [10] = {.lex_state = 1, .external_lex_state = 2},
  [11] = {.lex_state = 1, .external_lex_state = 2},
  [12] = {.lex_state = 1, .external_lex_state = 2},
  [13] = {.lex_state = 1, .external_lex_state = 2},
  [14] = {.lex_state = 3, .external_lex_state = 2},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_document_token1] = ACTIONS(1),
    [anon_sym_TAB] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
    [aux_sym_number_token1] = ACTIONS(1),
    [aux_sym_number_token2] = ACTIONS(1),
    [aux_sym_float_token1] = ACTIONS(1),
    [aux_sym_float_token2] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_empty_field] = ACTIONS(1),
    [sym__error_sentinel] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(37),
    [sym_row] = STATE(31),
    [sym_field] = STATE(18),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_TAB] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_float_token1] = ACTIONS(11),
    [aux_sym_float_token2] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_empty_field] = ACTIONS(15),
  },
  [STATE(2)] = {
    [sym_row] = STATE(38),
    [sym_field] = STATE(25),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_TAB] = ACTIONS(19),
    [sym_text] = ACTIONS(22),
    [aux_sym_number_token1] = ACTIONS(25),
    [aux_sym_number_token2] = ACTIONS(25),
    [aux_sym_float_token1] = ACTIONS(28),
    [aux_sym_float_token2] = ACTIONS(28),
    [anon_sym_true] = ACTIONS(31),
    [anon_sym_false] = ACTIONS(31),
    [sym_empty_field] = ACTIONS(34),
  },
  [STATE(3)] = {
    [sym_row] = STATE(30),
    [sym_field] = STATE(18),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [aux_sym_document_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(37),
    [anon_sym_TAB] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_float_token1] = ACTIONS(11),
    [aux_sym_float_token2] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_empty_field] = ACTIONS(15),
  },
  [STATE(4)] = {
    [sym_field] = STATE(22),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(39),
    [aux_sym_document_token1] = ACTIONS(39),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_float_token1] = ACTIONS(11),
    [aux_sym_float_token2] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_empty_field] = ACTIONS(15),
  },
  [STATE(5)] = {
    [sym_field] = STATE(22),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(41),
    [aux_sym_document_token1] = ACTIONS(41),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_float_token1] = ACTIONS(11),
    [aux_sym_float_token2] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_empty_field] = ACTIONS(15),
  },
  [STATE(6)] = {
    [sym_field] = STATE(22),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [ts_builtin_sym_end] = ACTIONS(43),
    [aux_sym_document_token1] = ACTIONS(43),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_float_token1] = ACTIONS(11),
    [aux_sym_float_token2] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_empty_field] = ACTIONS(15),
  },
  [STATE(7)] = {
    [sym_field] = STATE(36),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [aux_sym_document_token1] = ACTIONS(43),
    [sym_text] = ACTIONS(45),
    [aux_sym_number_token1] = ACTIONS(47),
    [aux_sym_number_token2] = ACTIONS(47),
    [aux_sym_float_token1] = ACTIONS(49),
    [aux_sym_float_token2] = ACTIONS(49),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [sym_empty_field] = ACTIONS(53),
  },
  [STATE(8)] = {
    [sym_field] = STATE(36),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [aux_sym_document_token1] = ACTIONS(39),
    [sym_text] = ACTIONS(45),
    [aux_sym_number_token1] = ACTIONS(47),
    [aux_sym_number_token2] = ACTIONS(47),
    [aux_sym_float_token1] = ACTIONS(49),
    [aux_sym_float_token2] = ACTIONS(49),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [sym_empty_field] = ACTIONS(53),
  },
  [STATE(9)] = {
    [sym_field] = STATE(36),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [aux_sym_document_token1] = ACTIONS(41),
    [sym_text] = ACTIONS(45),
    [aux_sym_number_token1] = ACTIONS(47),
    [aux_sym_number_token2] = ACTIONS(47),
    [aux_sym_float_token1] = ACTIONS(49),
    [aux_sym_float_token2] = ACTIONS(49),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [sym_empty_field] = ACTIONS(53),
  },
  [STATE(10)] = {
    [sym_field] = STATE(19),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_float_token1] = ACTIONS(11),
    [aux_sym_float_token2] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_empty_field] = ACTIONS(15),
  },
  [STATE(11)] = {
    [sym_field] = STATE(22),
    [sym_number] = STATE(20),
    [sym_float] = STATE(20),
    [sym_boolean] = STATE(20),
    [sym_text] = ACTIONS(7),
    [aux_sym_number_token1] = ACTIONS(9),
    [aux_sym_number_token2] = ACTIONS(9),
    [aux_sym_float_token1] = ACTIONS(11),
    [aux_sym_float_token2] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [sym_empty_field] = ACTIONS(15),
  },
  [STATE(12)] = {
    [sym_field] = STATE(26),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [sym_text] = ACTIONS(45),
    [aux_sym_number_token1] = ACTIONS(47),
    [aux_sym_number_token2] = ACTIONS(47),
    [aux_sym_float_token1] = ACTIONS(49),
    [aux_sym_float_token2] = ACTIONS(49),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [sym_empty_field] = ACTIONS(53),
  },
  [STATE(13)] = {
    [sym_field] = STATE(36),
    [sym_number] = STATE(32),
    [sym_float] = STATE(32),
    [sym_boolean] = STATE(32),
    [sym_text] = ACTIONS(45),
    [aux_sym_number_token1] = ACTIONS(47),
    [aux_sym_number_token2] = ACTIONS(47),
    [aux_sym_float_token1] = ACTIONS(49),
    [aux_sym_float_token2] = ACTIONS(49),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [sym_empty_field] = ACTIONS(53),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(17), 3,
      sym_empty_field,
      ts_builtin_sym_end,
      anon_sym_TAB,
    ACTIONS(55), 7,
      sym_text,
      aux_sym_number_token1,
      aux_sym_number_token2,
      aux_sym_float_token1,
      aux_sym_float_token2,
      anon_sym_true,
      anon_sym_false,
  [15] = 4,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 1,
      aux_sym_document_token1,
    ACTIONS(61), 1,
      anon_sym_TAB,
    STATE(15), 1,
      aux_sym_row_repeat1,
  [28] = 4,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      aux_sym_document_token1,
    ACTIONS(66), 1,
      anon_sym_TAB,
    STATE(15), 1,
      aux_sym_row_repeat1,
  [41] = 4,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(68), 1,
      aux_sym_document_token1,
    ACTIONS(70), 1,
      anon_sym_TAB,
    STATE(15), 1,
      aux_sym_row_repeat1,
  [54] = 4,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 1,
      aux_sym_document_token1,
    ACTIONS(76), 1,
      anon_sym_TAB,
    STATE(16), 1,
      aux_sym_row_repeat1,
  [67] = 4,
    ACTIONS(39), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 1,
      aux_sym_document_token1,
    ACTIONS(66), 1,
      anon_sym_TAB,
    STATE(17), 1,
      aux_sym_row_repeat1,
  [80] = 2,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
    ACTIONS(80), 2,
      aux_sym_document_token1,
      anon_sym_TAB,
  [88] = 2,
    ACTIONS(82), 1,
      ts_builtin_sym_end,
    ACTIONS(84), 2,
      aux_sym_document_token1,
      anon_sym_TAB,
  [96] = 2,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    ACTIONS(59), 2,
      aux_sym_document_token1,
      anon_sym_TAB,
  [104] = 2,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 2,
      aux_sym_document_token1,
      anon_sym_TAB,
  [112] = 3,
    ACTIONS(68), 1,
      aux_sym_document_token1,
    ACTIONS(90), 1,
      anon_sym_TAB,
    STATE(27), 1,
      aux_sym_row_repeat1,
  [122] = 3,
    ACTIONS(74), 1,
      aux_sym_document_token1,
    ACTIONS(92), 1,
      anon_sym_TAB,
    STATE(29), 1,
      aux_sym_row_repeat1,
  [132] = 3,
    ACTIONS(64), 1,
      aux_sym_document_token1,
    ACTIONS(94), 1,
      anon_sym_TAB,
    STATE(24), 1,
      aux_sym_row_repeat1,
  [142] = 3,
    ACTIONS(59), 1,
      aux_sym_document_token1,
    ACTIONS(96), 1,
      anon_sym_TAB,
    STATE(27), 1,
      aux_sym_row_repeat1,
  [152] = 2,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 2,
      aux_sym_document_token1,
      anon_sym_TAB,
  [160] = 3,
    ACTIONS(64), 1,
      aux_sym_document_token1,
    ACTIONS(94), 1,
      anon_sym_TAB,
    STATE(27), 1,
      aux_sym_row_repeat1,
  [170] = 2,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 1,
      aux_sym_document_token1,
  [177] = 2,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
    ACTIONS(105), 1,
      aux_sym_document_token1,
  [184] = 1,
    ACTIONS(80), 2,
      aux_sym_document_token1,
      anon_sym_TAB,
  [189] = 1,
    ACTIONS(88), 2,
      aux_sym_document_token1,
      anon_sym_TAB,
  [194] = 1,
    ACTIONS(101), 2,
      aux_sym_document_token1,
      anon_sym_TAB,
  [199] = 1,
    ACTIONS(84), 2,
      aux_sym_document_token1,
      anon_sym_TAB,
  [204] = 1,
    ACTIONS(59), 2,
      aux_sym_document_token1,
      anon_sym_TAB,
  [209] = 1,
    ACTIONS(107), 1,
      ts_builtin_sym_end,
  [213] = 1,
    ACTIONS(105), 1,
      aux_sym_document_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(14)] = 0,
  [SMALL_STATE(15)] = 15,
  [SMALL_STATE(16)] = 28,
  [SMALL_STATE(17)] = 41,
  [SMALL_STATE(18)] = 54,
  [SMALL_STATE(19)] = 67,
  [SMALL_STATE(20)] = 80,
  [SMALL_STATE(21)] = 88,
  [SMALL_STATE(22)] = 96,
  [SMALL_STATE(23)] = 104,
  [SMALL_STATE(24)] = 112,
  [SMALL_STATE(25)] = 122,
  [SMALL_STATE(26)] = 132,
  [SMALL_STATE(27)] = 142,
  [SMALL_STATE(28)] = 152,
  [SMALL_STATE(29)] = 160,
  [SMALL_STATE(30)] = 170,
  [SMALL_STATE(31)] = 177,
  [SMALL_STATE(32)] = 184,
  [SMALL_STATE(33)] = 189,
  [SMALL_STATE(34)] = 194,
  [SMALL_STATE(35)] = 199,
  [SMALL_STATE(36)] = 204,
  [SMALL_STATE(37)] = 209,
  [SMALL_STATE(38)] = 213,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [22] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [28] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 3, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 4, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [51] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_row, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_row, 3, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_row, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_row, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_field, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_field, 1, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_number, 1, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_number, 1, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_row_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float, 1, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float, 1, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [107] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_empty_field = 0,
  ts_external_token__error_sentinel = 1,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_empty_field] = sym_empty_field,
  [ts_external_token__error_sentinel] = sym__error_sentinel,
};

static const bool ts_external_scanner_states[3][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_empty_field] = true,
    [ts_external_token__error_sentinel] = true,
  },
  [2] = {
    [ts_external_token_empty_field] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_tsv_external_scanner_create(void);
void tree_sitter_tsv_external_scanner_destroy(void *);
bool tree_sitter_tsv_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_tsv_external_scanner_serialize(void *, char *);
void tree_sitter_tsv_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_tsv(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_tsv_external_scanner_create,
      tree_sitter_tsv_external_scanner_destroy,
      tree_sitter_tsv_external_scanner_scan,
      tree_sitter_tsv_external_scanner_serialize,
      tree_sitter_tsv_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
